# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-11 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Microtasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=40)),
                ('body', models.TextField(blank=True, null=True)),
                ('percentage', models.IntegerField(blank=True, default=0, null=True)),
                ('assigned_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.State')),
                ('ticket_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_rel_mtask', to='core.Ticket')),
            ],
        ),
    ]
