# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-07 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status_rel',
        ),
        migrations.AddField(
            model_name='user',
            name='test',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
