# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-21 05:37
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('comment', models.TextField(blank=True, null=True)),
                ('private', models.BooleanField(default=False)),
                ('ticket_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_rel_comm', to='core.Ticket')),
                ('user_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rel_comm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='commentsops',
            name='ticket_rel',
        ),
        migrations.RemoveField(
            model_name='commentsuser',
            name='ticket_rel',
        ),
        migrations.DeleteModel(
            name='CommentsOps',
        ),
        migrations.DeleteModel(
            name='CommentsUser',
        ),
    ]
