# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-03 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rssfeed',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
