# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_state_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.FileField(default=1, upload_to='/avatar/'),
            preserve_default=False,
        ),
    ]
