# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-11 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_microtasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microtasks',
            name='assigned_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.State'),
        ),
    ]
