# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-23 17:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_rssfeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='microtasks',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
