# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-08 17:20
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160807_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='color',
            field=colorfield.fields.ColorField(default='#008ac6', max_length=10),
        ),
    ]
