# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-08 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_state_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='color',
            field=models.CharField(default='#008ac6', max_length=10),
        ),
    ]
