# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-22 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160822_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='percentage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
