# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160227_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notify_email',
            field=models.BooleanField(default=False),
        ),
    ]
