# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-25 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160822_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='statecode',
            field=models.CharField(default='[TRM]', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='state',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
