# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-08 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160808_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='color',
            field=models.CharField(blank=True, default='#008ac6', max_length=10, null=True),
        ),
    ]
