# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 16:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_notify_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='create_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
