# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-25 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160825_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='numvalue',
        ),
        migrations.RemoveField(
            model_name='state',
            name='shortcode',
        ),
        migrations.AddField(
            model_name='queue',
            name='description',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='queue',
            name='shortcode',
            field=models.CharField(default='[TRM]', max_length=10),
            preserve_default=False,
        ),
    ]
