# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-15 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160810_0141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField(protocol='ipv4')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company_rel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Company')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='group_rel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.InventoryGroup'),
        ),
    ]
