# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_prio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Priority'),
            preserve_default=False,
        ),
    ]
