# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ticket_assigned_prio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Company'),
        ),
    ]
