# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-28 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='log_ticket',
            field=models.ForeignKey(default=40, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_log', to='core.Ticket'),
            preserve_default=False,
        ),
    ]
