# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rights',
            name='dept',
        ),
        migrations.AddField(
            model_name='rights',
            name='dept_dst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dst_dept', to='core.Department'),
        ),
        migrations.AddField(
            model_name='rights',
            name='dept_src',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='src_dept', to='core.Department'),
        ),
    ]
