# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('core', '0011_auto_20160320_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rights',
            name='dept_src',
        ),
        migrations.AddField(
            model_name='rights',
            name='grp_src',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
