# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20160321_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='rights',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rights',
            name='grp_src',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='src_grp', to='auth.Group'),
        ),
    ]
