# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20160321_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rights',
            old_name='dept_dst',
            new_name='dpt_dst',
        ),
    ]
