# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-13 01:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20160321_1614'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='Queue',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='department',
            new_name='queue',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='assigned_department',
            new_name='assigned_queue',
        ),
    ]
