# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-13 01:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20160613_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rights',
            name='dpt_dst',
        ),
        migrations.AddField(
            model_name='rights',
            name='queue_dst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dst_queue', to='core.Queue'),
        ),
    ]
