# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-02 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20160701_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file_name',
            field=models.FileField(blank=True, null=True, upload_to='static/ticket_files/'),
        ),
    ]
