# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-02 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20160702_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='ticket_rel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Ticket'),
        ),
    ]
