# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-24 18:45
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file_name',
            field=models.FileField(blank=True, null=True, upload_to=core.models.get_attachment_upload_path),
        ),
    ]
