# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170202_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='collapsednavbar',
            field=models.BooleanField(default=False),
        ),
    ]
