# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-20 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_collapsednavbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='labels',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
