# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-24 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_collapsednavbar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
